In [22]:
from matplotlib import pyplot
from matplotlib import numpy
%matplotlib inline

In [23]:
#Parameters
nx = 41
ny = 41

l = 1.
h = 1.

dx = l/(nx-1)
dy = h/(ny-1)

l1_target = 1e-6

In [24]:
def L1norm(new, old):
    norm = numpy.sum(numpy.abs(new-old))
    return norm

In [25]:
x = numpy.linspace(0, 1, nx)
y = numpy.linspace(0, 1, ny)
omega = numpy.zeros((nx, ny))
thesi = numpy.zeros_like(omega)

In [13]:
def Stokes_flow(dx, dy, omega, thesi, l1_target):
    
    l2norm = 1
    omega_n = numpy.empty_like(omega)
    thesi_n = numpy.empty_like(thesi)
    
    while l2norm > l1_target:
        
        omega_n = omega.copy()
        thesi_n = thesi.copy()
        
        omega[1:-1, 1:-1] = 0.25 * (omega_n[:-2, 1:-1] + omega_n[2:, 1:-1]\
                                   + omega_n[1:-1, :-2] + omega_n[1:-1, 2:])
        thesi[1:-1, 1:-1] = 1/(2*(dx**2 + dy**2)) * \
                            ((thesi_n[1:-1,2:] + thesi_n[1:-1,:-2])*dy**2\
                             + (thesi_n[2:,1:-1] + thesi_n[:-2,1:-1])*dx**2\
                             + omega_n[1:-1,1:-1]*dx**2*dy**2)
        #boundary conditions
        #top
        omega[-1,:] = -1/(2*dy**2)*(8*thesi[-2,:] - thesi[-3,:]) - 3*1/dy
        #bottom
        omega[0,:] = -1/(2*dy**2)*(8*thesi[1,:] - thesi[2,:])
        #left
        omega[:,0] = -1/(2*dx**2)*(8*thesi[:,1] - thesi[:,2])
        #right
        omega[:,-1] = -1/(2*dx**2)*(8*thesi[:,-2] - thesi[:,-3])
        
        a_1 = L1norm(omega, omega_n)
        a_2 = L1norm(thesi, thesi_n)
        
        l2norm = max(a_1, a_2)
        
    result = numpy.array([omega, thesi])
    return result
        

In [14]:
numpy.shape(thesi)

(41, 41)

In [15]:
final_result = Stokes_flow(dx, dy, omega, thesi, l1_target)

In [17]:
final_result[0]

array([[ -0.00000000e+00,  -7.28763699e-03,  -1.37943448e-02, ...,
         -1.37943448e-02,  -7.28763699e-03,  -0.00000000e+00],
       [ -7.31261353e-03,   2.04601149e-03,   1.14128837e-02, ...,
          1.14128837e-02,   2.04601149e-03,  -7.31261353e-03],
       [ -1.39941571e-02,   1.13714128e-02,   3.23148136e-02, ...,
          3.23148136e-02,   1.13714128e-02,  -1.39941571e-02],
       ..., 
       [  2.84608780e+01,   3.17800898e+00,  -7.89273450e+00, ...,
         -7.89273450e+00,   3.17800898e+00,   2.84608780e+01],
       [  3.61967434e+01,  -1.53446715e+01,  -2.25607772e+01, ...,
         -2.25607772e+01,  -1.53446715e+01,   3.61967434e+01],
       [ -0.00000000e+00,  -7.81926612e+01,  -4.66543587e+01, ...,
         -4.66543587e+01,  -7.81926612e+01,  -0.00000000e+00]])

numpy.shape(final_result[0])

In [18]:
final_result[-1]

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.41429633e-06,   2.17360372e-06, ...,
          2.17360372e-06,   1.41429633e-06,   0.00000000e+00],
       [  0.00000000e+00,   2.20482440e-06,   1.45898838e-07, ...,
          1.45898838e-07,   2.20482440e-06,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,  -6.35061518e-03,  -1.52288240e-02, ...,
         -1.52288240e-02,  -6.35061518e-03,   0.00000000e+00],
       [  0.00000000e+00,  -7.32622358e-03,  -1.33638594e-02, ...,
         -1.33638594e-02,  -7.32622358e-03,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

In [32]:
abs_thesi = numpy.abs(final_result[-1])
abs_thesi

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.41429633e-06,   2.17360372e-06, ...,
          2.17360372e-06,   1.41429633e-06,   0.00000000e+00],
       [  0.00000000e+00,   2.20482440e-06,   1.45898838e-07, ...,
          1.45898838e-07,   2.20482440e-06,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,   6.35061518e-03,   1.52288240e-02, ...,
          1.52288240e-02,   6.35061518e-03,   0.00000000e+00],
       [  0.00000000e+00,   7.32622358e-03,   1.33638594e-02, ...,
          1.33638594e-02,   7.32622358e-03,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

In [31]:
c = numpy.max(positive_thesi)
c

0.099845172462224338

In [33]:
abs_omega = numpy.abs(final_result[0])
abs_omega

array([[  0.00000000e+00,   7.28763699e-03,   1.37943448e-02, ...,
          1.37943448e-02,   7.28763699e-03,   0.00000000e+00],
       [  7.31261353e-03,   2.04601149e-03,   1.14128837e-02, ...,
          1.14128837e-02,   2.04601149e-03,   7.31261353e-03],
       [  1.39941571e-02,   1.13714128e-02,   3.23148136e-02, ...,
          3.23148136e-02,   1.13714128e-02,   1.39941571e-02],
       ..., 
       [  2.84608780e+01,   3.17800898e+00,   7.89273450e+00, ...,
          7.89273450e+00,   3.17800898e+00,   2.84608780e+01],
       [  3.61967434e+01,   1.53446715e+01,   2.25607772e+01, ...,
          2.25607772e+01,   1.53446715e+01,   3.61967434e+01],
       [  0.00000000e+00,   7.81926612e+01,   4.66543587e+01, ...,
          4.66543587e+01,   7.81926612e+01,   0.00000000e+00]])

In [34]:
c_1 = numpy.max(abs_omega)
c_1

78.192661228600699

In [36]:
thesi_1 = final_result[-1]
numpy.round(thesi_1[32,::8], 4)

array([ 0.    , -0.0575, -0.0944, -0.0944, -0.0575,  0.    ])