In [7]:
import numpy
from math import sin
p = 7.0
r = numpy.array([11.2, 4.7, 6.6])
for i in r:
    print(sin(p/i)**3)

0.20030150930292323
0.9900910096418035
0.6645423764180455


In [8]:
numpy.sin(p/r)

array([ 0.58509727,  0.99668603,  0.87265161])

In [9]:
a = numpy.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
b = numpy.array([3, 6, 9, 12,15])
b

array([ 3,  6,  9, 12, 15])

In [11]:
c = numpy.empty(5)

In [12]:
for i in range(5):
    c[i] = a[i] + b[i]

In [13]:
print(c)

[  4.   8.  12.  16.  20.]


In [14]:
c[:] = a[:] + b[:]

In [15]:
print(c)

[  4.   8.  12.  16.  20.]


In [16]:
d = numpy.empty(4)

In [17]:
d = a[:-1] + b[1:]
d

array([ 7, 11, 15, 19])

In [20]:
p = 7
r = numpy.array([11.2, 4.7, 6.6])

In [22]:
for i in r:
    print(sin(p/i)**3)

0.20030150930292323
0.9900910096418035
0.6645423764180455
